FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --include=dev

COPY . .

ARG VITE_PM_BASE_PATH=/
ARG VITE_PM_SITE_URL=https://www.manydoorsai.com
ARG VITE_PM_SUPPORT_EMAIL=info@manydoorsai.com
ARG VITE_PM_CHAT_URL=https://us-central1-property-managment-a5ed3.cloudfunctions.net/pmGatewayChat
ARG VITE_PM_FIREBASE_API_KEY=AIzaSyAuYn4nm9jTIcdFeNStmLF_Ky8qgwe4R2M
ARG VITE_PM_FIREBASE_AUTH_DOMAIN=property-managment-a5ed3.firebaseapp.com
ARG VITE_PM_FIREBASE_PROJECT_ID=property-managment-a5ed3
ARG VITE_PM_FIREBASE_STORAGE_BUCKET=property-managment-a5ed3.firebasestorage.app
ARG VITE_PM_FIREBASE_MESSAGING_SENDER_ID=742597343666
ARG VITE_PM_FIREBASE_APP_ID=1:742597343666:web:d04e9435b5fdaafa048cab
ARG VITE_PM_FIRESTORE_DB=property-managment
ARG VITE_EMAILJS_SERVICE_ID=
ARG VITE_EMAILJS_TEMPLATE_ID=
ARG VITE_EMAILJS_PUBLIC_KEY=

ENV VITE_PM_BASE_PATH=$VITE_PM_BASE_PATH
ENV VITE_PM_SITE_URL=$VITE_PM_SITE_URL
ENV VITE_PM_SUPPORT_EMAIL=$VITE_PM_SUPPORT_EMAIL
ENV VITE_PM_CHAT_URL=$VITE_PM_CHAT_URL
ENV VITE_PM_FIREBASE_API_KEY=$VITE_PM_FIREBASE_API_KEY
ENV VITE_PM_FIREBASE_AUTH_DOMAIN=$VITE_PM_FIREBASE_AUTH_DOMAIN
ENV VITE_PM_FIREBASE_PROJECT_ID=$VITE_PM_FIREBASE_PROJECT_ID
ENV VITE_PM_FIREBASE_STORAGE_BUCKET=$VITE_PM_FIREBASE_STORAGE_BUCKET
ENV VITE_PM_FIREBASE_MESSAGING_SENDER_ID=$VITE_PM_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_PM_FIREBASE_APP_ID=$VITE_PM_FIREBASE_APP_ID
ENV VITE_PM_FIRESTORE_DB=$VITE_PM_FIRESTORE_DB
ENV VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID
ENV VITE_EMAILJS_TEMPLATE_ID=$VITE_EMAILJS_TEMPLATE_ID
ENV VITE_EMAILJS_PUBLIC_KEY=$VITE_EMAILJS_PUBLIC_KEY

RUN npm run build

FROM nginx:1.27-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/app.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
